spring:
  datasource:
    url: jdbc:postgresql://psql01.mikr.us/db_c180
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:30180/eureka/
