spring:
  application:
    name: data-service
  datasource:
    url: jdbc:h2:mem:main-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/