spring:
  application:
    name: data-movie-service
  datasource:
    url: jdbc:h2:mem:movies-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /console
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/